# Generated by Django 5.1.4 on 2025-03-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentImage',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='PostVideo',
        ),
    ]
