# Generated by Django 5.1.4 on 2025-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
