# Generated by Django 5.1.4 on 2025-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_content_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers')], default='public', max_length=10),
        ),
    ]
